---
title: "Let's Get Started! - はじめてみよう"
output:
  html_document:
    df_print: paged
#    toc: yes
#    toc_float: yes
---

> Rstudio で `R` を使う、はじめの一歩. 
> `R` とは、RStudio.cloud の紹介、`R` と RStudio IDE の Install、簡単な使い方を説明します。  そのあとで、
> `R` の基本を学ぶ、Site の紹介をします。

## `R` and RStudio

### `R`

> R is ‘GNU S’, a freely available language and environment for statistical computing and graphics which provides a wide variety of statistical and graphical techniques: linear and nonlinear modelling, statistical tests, time series analysis, classification, clustering, etc.
> (https://cran.r-project.org)

`R` を管理している cran (The Comprehensive R Archive Network) にある、`R` の説明です。「統計解析とグラフ作成のための言語」とあり、様々な Data Analysis（データ解析）に対応していることがわかります。最初に、'GNU S' とありますが、GNU は、Free Software の意味だとして、Free の意味についても、[GNU](https://www.gnu.org/home.en.html) の Site に書かれています。'S' とありますが、これは、`R` の母体となっている、米国の、Bell Laboratories（ベル研究所）で開発された統計解析ソフトの名称です。

* [Richard Stallman's TEDx video: "Introduction to Free Software"](https://www.youtube.com/watch?v=dKmkcadmIu8): GNU の創始者の Richard Stallman の TED での TALK の Youtube Video です。なにが、Free Software かを語っています。英語の字幕を見ることができます。[13'39'']

### RStudio.cloud

> Let's try `R` on online! `R` を [RStudio.cloud](https://rstudio.cloud)  を使って Online で。

`R` は RStudio を使って利用することが一般的になっています。`R` や RStudio (desktop RStudio IDE) も Free（無償）で、Local な Computer に Install することが可能ですが、まずは、Online で `R` を RStudio で使う方法を紹介します。大学・研究機関などでは、RStudio Server を導入しているところも多いと思いますが、ここでは、Free Open Online な、RStudio.cloud を紹介します。

* **Account の取得から Login まで**
  1. [RStudio.cloud](https://rstudio.cloud) に Access します。
  2. 右上の Sign Up を click。
  3. Email を入力すると、Password の提案ができますが、使用しないとして、Password を設定、First Name, Last Name を入力します。Sign Up をクリックすると、アカウントが作成されます。名前をどうするか聞かれますが、それを決めれば、完了です。Your Workspace という画面に移ります。  
      * [Alternative] 他の方法として、Sign Up with Google と、Sing Up with Github があります。自分の Google や、Github のアカウントとリンクすることでもアカウントを作成できます。その場合は、それぞれのアカウントの Password を入力してください。すでに、Google の自分のアカウントに Login していれば、Password は不要です。
  4. New Project を Click または、Project 名を入れて Click すれば、Project が立ち上がります。Project 名を入れてみてください。Learning R などでも良いですよ。あとから、Project 名を入れることもできます。ここからは、Local で RStudio を利用する場合と殆ど同じですから、別途説明します。
  5. 右上の名前を選び、Logout すれば、終了できます。
  6. アカウントができていて Login するときは、Sign In を選択し、アカウントで使った、Email Address を入力します。自分しか使わない、Laptop PC などで、Login のときなど、他の形で、Security が保てる場合には、Login 情報を保存しておけば、簡単に、Sign In できますが、危険もありますので、十分注意してください。

* **RStudio.cloud** について
  * 2020年3月時点では、beta 版となっており、開発途上であることを示しています。
  * [RStudio.cloud Guide](https://rstudio.cloud/learn/guide): 基本的な解説があります。  
  * 25 Projects が上限、公開・非公開・限定公開を選べますが、共同で編集する場合は、10人が上限、1 Project 毎に 1GB が上限とあります。[2020.3.12]

* **RStudio.cloud** での `R` の利用について
  * 基本的に、desktop RStudio IDE の使い方と同じですので、対応する項をみてください。
 

### Local Installation of `R` and RStudio

> 自分のコンピュータに、`R` や、RStudio を Install しましょう。
> しばらくは、Online だけで学びたい場合は、この節は飛ばしてください。

インターネットが自由に使えない環境にいる場合もあるでしょうし、RStudio はまだ、beta 版ですから、個人で使える、パソコンがある場合には、`R` や、Rstudio を Install しておきましょう。まず、`R` を Install してから、RStudio を Install します。

* **`R` の Download and Installation**
  1. [CRAN](https://cran.r-project.org/) に Access します。
  2. Download R for Linux, Download R for (Mac) OS X, Download R for Windows と並んでいます。Linux, Mac, Windows を選択して、Click してください。  
    a. Windows では、Install R for the first time と base のところにありますから、それを選択、Install してください。  
    b. Mac では、Latest Release とあるものを、Install しますが、古い Operaton System (OS) を使っている場合は、説明を読んで、適切なものを選択してください。OS の version が不明のときは、Mac の左上の、リンゴマークの「このMacについて」から情報を得てください。
  3. あとは、他の Software の Installation と同じです。指示に従ってください。
  4. Version は、三つの数字からなっており、3.x.y 形式になっています。このページを compile しているのは、`r R.version.string` となっています。二番目の x の部分は、ほぼ一年間に一つずつ大きくなり、3.6.y は 2019年、3.7.y は2020年のものなどとなっています。三番目は、minor change の version となります。

この `R` を、Application として立ち上げれば、Console が現れ、そのまま使えますが、`R` の Integrated Development Environment（IDE 総合開発環境）である、RStudio IDE を導入します。


* **RStudio IDE の Download and Installation**
  1. [RStudio](https://rstudio.com/) に Access します。
  2. 一番上の Download を Click します。
  3. RStudio Desktop IDE,  Open Source License, Free と書いてあるものを、Download し、他の Application と同じように Install します。
  4. Application として、RStudio を立ち上げます。すると、RStudio.cloud で、Project を立ち上げたときと似た画面が出てきます。上の Menu Bar の File の上の方（おそらく上から二番目）にある New Project を選択します。新しい Project を Computer のどこに Save するかと、Project 名を入力します。何でもかまいませんが、Learning R でもよいでしょう。すると、右端に、Project 名が入ります。ここまでで、RStudio.cloud の項で述べた状態とほぼ同じになります。

* R や、RStudio の Installation でつまずいてしまったら、[Youtube](https://www.youtube.com) で、Install R and RStudio, Windows [または Mac] と入れて検索してください。video がいくつも見つかります。英語がわかりにくいときは、字幕を出して確認して、Install してください。

RStudio Desktop IDE, Open Source License, Free, そして Download と書いてある下に、Learn More とありますから、それを、Click すると、仲程に、'Take a tour of RStudio’s IDE' と書いてある、Video があります。ざっと見てみるのもよいでしょう。なとなく、概要（雰囲気）がわかります。

さらに、CLICK HERE TO SEE MORE RSTUDIO FEATURES へと進むと、もう少し情報を得ることができます。急ぐ必要はありません。使い始めてから、[このページ](https://rstudio.com/products/rstudio/features/) に戻ってくるとよいでしょう。


### Let's Try `R` on RStudio

> ここまでで、準備 OK です。RStudio.cloud または、RStudio Desktop IDE で R を使うことができるようになりました。  

ほんの少し、RStudio 上で、`R` を使ってみましょう。

#### Step 1. Console and Panes

* RStudio には、[たくさんの Cheat Sheets](https://rstudio.com/resources/cheatsheets/)（カンニング・ペーパー）とよばれるものが、用意されています。とても、便利です。（[RStudio の Top Page](https://rstudio.com/) の Resources から見ることができます）まずは、RStudio IDE の Cheat Sheet を見てみましょう。
  - [RStudio IDE Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/rstudio-ide.pdf) [Download English Version] 
  - [RStudio IDE Cheat Sheet translated by Masato Takahashi](https://github.com/rstudio/cheatsheets/raw/master/translations/japanese/rstudio-IDE-cheatsheet_ja.pdf) [Download Japanese Version] このように、いくつかの Cheat Sheets は日本語に訳されています。Cheat Sheets のページの下の方を探してください。
* 上に Menu Bar があり、下が、通常は、4つの枠に別れています。これを pane と言います。隠れている場合もあります。Maximize（最大化）すると現れるようになっています。左下の pane に Console という Tab（タブ）があると思います。起動時には、これが開いていると思いますが、開いていなければ、それを選択して開いてみてください。左下の Pane が、Console になります。
* Console に、$>$ が表示されていると思います。そこに、`3+5` といれて、Enter (Enter Key, Carriage Return (CR) でもかまいません）してください。[1] 8 と出て、新しい、$>$ が現れます。次に、`7*24` と入れてみてください。[2] 168 一週間の時間数が現れます。次に、`plot(cars)` と入力してみてください。右下の pane の Plots Tab に、下のようなグラフが現れるはずです。
```{r echo = FALSE}
plot(cars)
```
* `R` には、付属のデータがたくさんついていて、これは、Speed and Stopping Distances of Cars（自動車のスピードと制動距離）のデータです。右下の pane に Help という Tab があると思います。その pane の右上に、虫眼鏡マークの、Search Box があると思いますから、そこに、cars と小文字で入れてみてください。その情報が現れます。今度は、その Search Box に、plot と入れてみてください。manual（説明）が現れます。
* 今度は、右上の pane から、History（履歴）tab を見つけて、選択してください。すると、いままでに、Console に打ち込んだ、Command（命令）`3+5`, `7*24`, `plot(cars)` が現れると思います。

#### Step 2. Package Installation and `swirl`

* `R` には、現在、15000を越える、あるプロセスで、公式に認証された packages があります。Open Software ということで、世界中の users が、program（data が含まれる場合もあります） を作成して、形式を整えて、登録してあり、それを利用することができます。
* 一つの package が他の package に関連していたり、依存していたりするため、これを利用するときには、その依存関係も考慮に入れて、Install する必要があります。
Rstudio では、このことも考慮して、簡単に Install できるようになっています。しかし、一つの機能が、二つの package で異なる形で、拡張されることもあるため、package の Installation は、能動的に行うようになっています。
* たとえば、よく使われる、`tidyverse` という package の場合には、利用するときには、`ggplot2`, `purrr`, `tibble`, `dplyr`, `tidyr`, `stringr`, `readr`, `forcats` と 8つの package を同時によみこむようになっています。さらに、Install するときには、他の関連する packages も、読み込まれます。いずれ使うようになりますので、Install してみましょう。
* Menu Bar の Tools から、Install Packages ... を選択します。Packages という枠に、`tidyverse` と入力してみてください。途中まで入力すると、候補がいろいろと現れ、最後、spell を間違っていなければ、`tidyverse` だけが残りますから、Install ボタンを押してください。ちょっと時間がかかりますが、Console に次々とメッセージが現れ、最後に $>$ が現れます。RStudio IDE のときは、どこから、Download するかを聞かれるかもしれませんが、そのときは、どれかを選んでください。近いところのほうが一般的には Install の時間が短くなります。どのようなものか見たいときには、また、右下の pane から、Help tab を選んで、`tidyverse` と入れてみてください。`vignette` と現れ、その右に、選択肢が現れます。manual よりもう少し、詳しい情報が、わかりやすくかかれているものが、`vignette` です。すべての package にあるわけではありませんが、manual だけでは、わからないことも多いので、これがあると有効です。

> ちょっと小休止。ここまでを Video と Exercise で確認してみませんか。Skip してもかまいません。  
> [確認とExercise](https://learnr-examples.shinyapps.io/ex-setup-r/#section-install-r)
> （`learnr` で作成されています。`learnr` に興味のあるかたは、この Link の左にある [Welcome](https://learnr-examples.shinyapps.io/ex-setup-r/) および、[`learnr`](https://rstudio.github.io/learnr/index.html) を参照してください。）

* もう一つ、`swirl` package を Install してみましょう。同じように、Menu Bar の Tools から、Install Packages ... を選択します。Packages という枠に、`swirl` と入力して、Install です。[`swirl`](https://swirlstats.com) は、Johns Hopkins University で開発された、学習用の package で、これを作るための、package も用意されています。`swirlify` です。
* 使ってみましょう。package は、Install しただけでは、使えません。使うよと宣言します。それが、`library("swirl")` です。quotation mark は、この場合、なくても可ですが、入れる習慣をつけておくとよいでしょう。場合によっては、問題が起こることもないとはいえません。Console の $>$ の次に、`library("swirl")`　として Enter、そして、`swirl()` と入力すると、学習プログラムが始まります。ちょっとした説明のあと、"What shall I call you?" とでます。名前でも、Nickname でも、イニシャルでも入れてください。このあとは、あなたのことを、この名前で呼ばれます。そのあとは、"..." まで読んだら、Enter と言う説明がありますから、また Enter。1 Continue., 2 Proceed. , 3 Let's get going! の選択がでます。どれでもよいので、番号を入力してください。次に、途中でどうするかの説明があります。ともかくやめたいときは、ESC（Escape Key）、$>$ が出ていて、そこまでを保存してやめたいときは、`quit()` 他にも、いくつも選択肢があることがわかります。次には、1: R Programming 2: Take me to the swirl course repository!　と出ます。1 を選ぶのがよいでしょう。2 を選ぶと、Pop-up window が出ます。Browser がそれを、Pop-up を表示しない設定になっていると、一旦終わります。1 を選ぶと、1-15 の項目が現れます。どれからでもよいですが、`R` について何も知らない場合は、1 からトライしてみてください。$>$ が出ているときには、`quit()`、$>$ が出ていないときに、ともかくやめたいときは、ESC です。Interactive Lesson を楽しんでみてください。
* [日本語での説明と例](examples/swirl.html)：英語での演習に抵抗があるかたのために、作成しました。少しずつ、英語に慣れていけるとよいですね。
* 音声がありませんが、`swirl` のサイトから、簡単な Youtube Video にリンクがあります。それを見てみるのもよいでしょう。最初のビデオは、最初の module あとのビデオでは、15 Basic Graphics を選んでいます。三つ目は、説明もあり、`R` と、RStudio の Installation から説明しています。
  * [Learning R interactively with Swirl by Jonghyun Lee](https://www.youtube.com/watch?v=0ksZmNU5FRM) [5'39'']
  * [Learn R interactively via Swirl by Yimi Zhao](https://www.youtube.com/watch?v=McoHQIxJd-o) [1'37'']
  * [Learn to Program R in R! Intro to Swirl by BurkeyAcademy](https://www.youtube.com/watch?v=6azsCcyJ-lM)

続けて、`swirl` でしばらく学ぶのも良いでしょう。他の、Learning Resource を、下で紹介しますが、その前に、RStudio での次の大切なステップを紹介します。

#### Step 3. R Scripts

> `R` の一つ一つの、Command であっても、保存しておくことが重要になります。  
> ある程度の長さのプログラムになれば、なおのことです。Reproducibility（再現性）のためにも、大切です。Console ではなく、R Script を使って、記録します。

* RStudio の Menu Bar の File から、R Script を選択します。左上の pane に、Untitled1 などと書かれた枠ができます。
* RStudio の Menu Bar の File から、Save as ... を選択して、名前をつけて、保存してください。このときに、現在の、Project （desktop RStudio IDE の場合は、Project を作った Folder です。）の中に、新しいファイルができます。もし、新しい、Folder に入れたいときは、新たに作成して、Save してください。ここでは、test1 としてみます。RStudio.cloud を使っているときは、Browser（閲覧ソフト）を使っていて、それにも、名前を付けて保存（Save as ...）などがあると思いますから、それと間違わないでください。
* 下の、三行を、入力するか、copy & paste をしてください。
```
data(cars)
head(cars)
plot(cars)
```
* それぞれ改行していますが、なにも起こりません。ここで、左上の RScript の pane の右上にある、Source Pulldown Menu の Source を選んでください。なにか、動きがあり、右下には、以前も、生じた `plot(cars)` のグラフが現れたと思います。Source では、その RScript の最初からすべてを、実行します。Plots の pane には、Exports ボタンもありますので、画像として、取り出すことも可能です。また、Zoom で拡大することもできます。
* 右上の pane の Environments に Data, Values と現れたはずです。Data には、cars とあり、50 obj. 2 variables、Values には、x, y とあります。cars を Click すると、speed, dist の値が現れ、50 obj. 2 variables を Click すると、R Script があった pane に表があらわれます。Filter とも書いてあり、speed や dist のあたりを、さわると、順番の並べ替えも起こります。
* 左上の pane の、R Script のファイル名を選ぶと、R Script に戻ります。そこで、`head(cars)` の後ろに、マウスなどで、carret（入力位置）をおき、または、その行を highlight（選択）して、Run ボタンをおすと、`head(cars)` が実行されて、Console に、cars という data の最初の6行が現れます。一行または、highlight した箇所が実行されます。
* 右下の pane の Help の枠に、`head` と入れてみてください。Return the First or Last Part of an Object と出てきます。何も特別な指定をしないと、通常は、最初の6行が現れます。Help の一番下にある、Example を R Script のところに入れて、試してみるとよいでしょう。たとえば、`head(letters, n = -6L)` では何が現れますか。Help をよく読むとわかります。`letters` を、`cars` にするなどして、試してみてください。
* 右下の pane の Files を見ると、おそらく、三つファイルがあるのではないかと思います。.Rhistory, project.Rproj, それと、R Script のファイル名です。上で、test1 とファイル名を決めた場合には、test1.R とあると思います。ピリオッド以下の最後の部分を File extension（ファイル拡張子）といいますが、それが、R Script の場合には、.R になります。
* Menu bar の File から Save を選んで、保存すれば、そこまでの状態をあとから、Reproduce（再現）することも可能です。

どうですか。R Script の使い方、R Studio の機能、少し理解できましたか。

#### Step 4. R Markdown and notebook

> R Script などで、実行したことを、説明も含めて、R Markdown, Notebook で文書として記録することで、Reproducibility（再現性）だけでなく、Literate Programming（理解できるように記録する）ことが可能になります。

* RStudio の Menu Bar の New File から、今度は、Notebook を選択してください。すでに、なにやら、文章がはいったものが出てきます。読んでみてください。
* まず、[R Markdown](http://rmarkdown.rstudio.com) の Notebook であることで、R Markdown のリンクが書かれています。つぎに、Chunk（code chunk と呼ばれる、プログラムの塊で、例では、`plot(cars)` が ---{r} から --- までで囲まれている部分をさします。Run ボタン（Code Chunk の右上にある、右をむいた三角印のことです。）を押すか cursor（カーソル）をその Chunk の中に合わせて、Cmd+Shift+Enter を押すと、実行することができるとあります。やってみてください。この Chunk の下に、グラフが現れます。右上には、X がありますから、それ押せば消えます。
* このような Chunk を加えるには、Tool Bar の Insert Chunk（Insert ボタンを押すと一番上に、R とありますからそれを）を押すか、Cmd+Option+I とします。と、書いてあります。そこで、どこでも良いのですが、一番下まで、Cursor を持って行って、そこで、実行してみてください。すると、上の Chunk と似たもので、真ん中が一行空いたものが現れます。そこで、たとえば、`head(cars)` と書き入れてみてください。
* Preview と書いてあるボタンを押すか、`knit` とあり、knit to HTML, knit to PDF, knit to Word と選べるようになっているかもしれません。それを選択すると、HTML（ホームページの記述に標準的に使われる、Hypertext Markup Language）か、PDF（Portable Document Format）か、Microsoft Word file になります。RStudio.cloud では、最初、Pop-up が block されていると、表示されませんが、Retry をすれば、表示されると思います。
* HTML は通常問題ありませんが、PDF と、Word については、多少コメントが必要です。最初は読み飛ばしてください。  
  - PDF には、$\TeX$ という プログラムが使われています。RStudio.cloud には、最初から、Install されているようですが、通常は、`tinytex` というプログラムを Install します。また、日本語が含まれるときには、少し修正が必要です。別途解説します。特に、すでに、`LiveTeX` などを、Local に Install されているときは、調整が必要です。  
  - Word は、Default では、Paper Size が Letter になっています。A4 に変えるなどが必要です。[Word Document](https://bookdown.org/yihui/rmarkdown/word-document.html) に少し説明がありますが、出力した、Word File の Format をお好みに変えてから、my-styles.docx と名前を変えて、Project のある Folder に入れ、、一番上の `yaml` と言われる部分に、引用した箇所のように、`reference_docx: my-styles.docx` を加えれば、そのフォーマットで次から、output してくれます。  
  - [R Markdown](https://rmarkdown.rstudio.com) を参照してください。
* これで、HTML の文書が作れることがわかりました。Title: "R Notebook" を自分の好みに変え、日本語で説明の文書をを加えるなどして、R Notebook を作成してください。Reproducible and Literate Programming というものが、できるようになります。今後も、R Notebook を使って、自分のノートを作っておくと良いでしょう。
* 流れを復習します。R Script でプログラムを作成する。完成したら、R Notebook を作成、Code Chunk に、R Script の プログラムを挿入すれば、その結果を含んだ HTML 文書を作成することができます。
* Notebook ではなく、R Markdown を選択しても、基本的には同じです。ただ、最初に、出力形式を選択したり、名前を入れたりします。File Extention（拡張子）は、.Rmd でどちらも同じです。

> [R Markdown Overview](https://rmarkdown.rstudio.com/lesson-1.html): R Markdown の概要の Video を見てみませんか。

**Note 備考**

* `R` の update: Installation と同じ方法で行います。作業の途中はさけてください。挙動が変わる場合もたまにあります。`R.version` Command などで、version を確認して、net 上で調べてください。
* RStudio の update: Installation と同じ方法で行います。RStudio の About RStudio menu から version を確認できます。


### R Markdown

* R Markdown の基本は、RStudio の Menu Bar の Markdown Quick Reference を参照してください。
* R Markdown では、Homepage や、本の作成も可能です。詳細は、[R Markdown](http://rmarkdown.rstudio.com) を参照してください。
* [R Markdown Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)
* [R Markdown Reference Guide](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)

#### Markdown

> More information on Markdown Syntax and Markdown Editors

`R Markdown` を頻繁に使うようになると、RStudio の Help に書かれている情報より、もう少し詳しい説明が欲しくなります。 また、日本語入力において、RStudio では、困難を覚えることもあるかもしれません。

* [Pandoc's Markdown](https://pandoc.org/MANUAL.html#pandocs-markdown): RStudio の [Markdown のページ](https://rmarkdown.rstudio.com/lesson-8.html)からリンクがある Pandoc's Markdown に `Markdown` についての、正確な情報が書かれています。Pandoc は、universal document converter で、様々な Format（形式）の文書の、変換を行うもので、`R Markdown` の文書を、html や、MS Word file に、書き換えるときに、使われているものです。
* [Markdown Tutorials](https://www.markdowntutorial.com): Exercise 形式で、Markdown の Syntax（文法）について学べるようになっています。
* [DARING FIREBALL `Markdown` Dingus](https://daringfireball.net/projects/markdown/dingus): [DARING FIREBALL: Markdown] (https://daringfireball.net/projects/markdown/)] にある、Dingus（「なんとか言う奴」という程度の意味）。日本語入力のときは、RStudio と比較して、入力がスムーズです。Online の Markdown Editor として利用できます。Filter を Markdown、Results を Preview にして、Convert を押します。他にも、Online の Markdown Editor はいくつもあります。入力と同時に、Preview が表示されるものもあります。好みのものを探してください。
* [Cocalc](https://cocalc.com/): Collaborative Calculation and Data Science で、数式処理の SageMath、$\LaTeX$ Editor、Jupyter Notebook などが使え、`R` Console もあり、R Markdown も使えるようになっていますが、日本語は使えない、Package 管理の問題もあるため、詳細は紹介しませんが、個人的には、Markdown Editor としても使っています。



#### More on RStudio

> はじめて、`R` や RStudio に触れるひとは、この項は読み飛ばしてください。  
> [RStudio Site](https://rstudio.com) の上の Resources の Webinar & Videos を見てみましょう。`R` や Data Science を少し知っているので、先回りして、RStudio でできることを知りたい人にお勧めです。

ページの左に、次のようにあります。

* Learning Roadmap
  - RStudio Essentials
  - Data Science Essentials
  - Advanced Data Science
  - Working with Spark
  - Product: Connect
  - RStudio Pro Administration
  - Español Materials

* Events
  - Webinars
  - rstudio::conf by Year
  - rstudio::conf by Topic
  - Additional Talks

* Important RStudio Sites
  - shiny
  - R Markdown
  - tidyverse
  - Databases
  - sparklyr


## Manual and Online Help 

> `R` の文法、`R` や package の Command（命令）の詳細は膨大で覚えることは不可能です。  
> 基本をある程度理解し、あとは、Manual や、Help を調べ、Examples をとおして学びます。  
> Internet 上を検索して調べること、Blog などでの、Discussion から情報をえることも必要な場合が多いですが、まずは基本を理解しましょう。

### Manual and Introduction to `R`

> **Introduction to `R`** は、CRAN (The Comprehensive R Archive Network) で編集している、短い Manual です。常に Update し最新の情報になっています。

* [The R Manuals](https://cran.r-project.org): Manual の名称、R-release、R-pached、R-devel とあり、それぞれに、HTML, PDF, EPUB 形式のファイルが置かれています。
  - R-release: the most recent released R version （最新の公式版）
  - R-pached: a very current version for the patched release version（細かい修正を加えた新しい版）
  - R-devel: a version for the forthcoming R version（開発版）
* Introduction to `R` の日本語版も、Internet 上に、いくつか公開されています。構造が大きく変更になることは、あまりありませんし、三桁の version 名の最初の一つが同じならば、殆ど問題はないと思います。しかし、最新版というだけではなく、用語などを考えると、英語のものを利用する価値は十分にあると思います。また、実際に使うときには、他の、Site の英語の説明を参照することも多くなります。
* **Preface**: `R` についてなど、基本事項の紹介のあと、読者に二件書いてあります。  
  - _Most R novices will start with the introductory session in Appendix A. This should give some familiarity with the style of R sessions and more importantly some instant feedback on what actually happens._　まず "Appendix A A sample session" を見ると、`R` の実際についての基本についてわかります、とありますから、見てみることをお勧めします。
  - _Many users will come to R mainly for its graphical facilities. See Graphics, which can be read at almost any time and need not wait until all the preceding sections have been digested._ 二つ目として、グラフィックについて調べる場合が多いと思うので、他の箇所を十分理解してからでなくても、12. Graphical Procedures を読むことを勧めています。
  - 以上二件、ざっと見てみることをお勧めします。

### Online Help

> `R`には、膨大な packages があり、それを日常的に利用します。一つ一つの package については、Introdution to `R` には書かれていません。また、上の Manual ではなく、RStudio の画面などで、Help を利用する方が簡単です。Help の使い方を基本から紹介します。

* 'Introduction to `R`' の項でも紹介した、Appendix A の最初に、`help.start()` について、_Start the HTML interface to on-line help (using a web browser available at your machine). You should briefly explore the features of this facility with the mouse._ とあります。これを、RStudio の Console や、R Script で、command として実行（run）すると、RStudio の 右下の pane の Help に、'Statistical Data Analysis `R`' と現れ、最初に、'Introduction to `R`' が現れます。ここからも、この文書を見ることができます。'The `R` Language Definition'、'`R` Data Import/Export', 'Packages', '`R` Resources' は、すぐにでも役に立つと思います。
* RStudio で、`head`, `mean`（平均）, `sd`（標準偏差）, `plot`, `summary`, `tidyverse`, `ggplot2` などを調べたいとき. 
  1. Console または、R Script で、? を付けて検索。`?head` Enter。
  2. Console または、R Script で、?? を付けて検索。`??head` Enter。
  3. 右下の pane の Help Tab の右上の虫眼鏡マークに head などと入力。

それぞれどのように表示されるか、比較してみてください。

* `tidyverse` や `ggplot2` などの、重要な package の場合は、Vignette が表示され、かなり詳しい説明にアクセスできます。
* `plot` などで、Help に表示されるものが長い時は、さらに、検索が必要な場合もあります。RStudio の時には、虫眼鏡の次の行の Box に調べたい Key Word を入力すると、その Help のページ内で、検索してくれます。

Help の活用は、とても、有効ですから、Internet での情報を探す前に、まずは、Help を活用してください。


## Learning Sites

> `R` の基本を学びましょう。Interactive に学べるサイトと、Static な Online Contents を、実際に使ってみながら紹介していきます。  
> RStudio で紹介した、`swirl` も活用してください。

### RStudio Primers

> Interactive Tutorials が Free Open Online で提供されています。今後、Contents が増えていくことが期待されます。

* [RStudio Primers](https://rstudio.cloud/learn/primers): [RStudio.cloud](https://rstudio.cloud) の下からリンクがついています。Login なしで使えます。  
  1. [The Basics](https://rstudio.cloud/learn/primers/1): `ggplot2` 入門の、Visualization Basics と、Programing Basics にわかれています。最初から、`ggplot2` の package は load されています。もし、R Script や、R Markdown, Notebook などに記録するときは、最初に `library(ggplot2)` を実行してから始めてください。問題は [R for Data Science](https://r4ds.had.co.nz) からとられています。[Solutions to Exercises of R for Data Science](https://jrnold.github.io/r4ds-exercise-solutions/) の答えも公開されています。
  2. [Working with Data](https://rstudio.cloud/learn/primers/2): `R` の基本的なデータ形式は、Data Frame ですが、より、扱いやすい、`tibble` および、それをあつかう、`dplyr` package についての問題です。
  3. [Visualizing Data](https://rstudio.cloud/learn/primers/3): `ggplot2` で扱う、様々なグラフについての問題です。
  4. [Tidy Your Data](https://rstudio.cloud/learn/primers/4): `tidyverse` を学ぶ問題です。
  5. [Iterate](https://rstudio.cloud/learn/primers/5): `R` で Program を書くときに、必要なことを学びます。
  6. [Write Functions](https://rstudio.cloud/learn/primers/6): 関数を書いて利用するときに、必要なことを学びます。

### Swirl

> Console を利用して、対話型で学ぶコースを提供する、Package です。基本的なことは学べるコースがすでに用意されています。下のような説明があります。  
> Use the R console as an interactive learning
environment. Users receive immediate feedback as they are guided through self-paced lessons in data science and R programming.

* [{`swirl`} website](https://swirlstats.com): `swirl` の解説とともに、`swirl` を開発するための `swirlify` の説明もあります。
* [`swirl` Course Repository](https://github.com/swirldev/swirl_courses#swirl-courses)  
  - [Swirl Courses Organized by Title](https://swirlstats.com/scn/title.html): List of `swirl` courses
* [CRAN `swirl` Package](https://cran.r-project.org/web/packages/swirl/index.html), [Manual in PDF](https://cran.r-project.org/web/packages/swirl/swirl.pdf)
* [CRAN `swirlify` Package](https://cran.r-project.org/web/packages/swirlify/index.html), [Manual in PDF](https://cran.r-project.org/web/packages/swirlify/swirlify.pdf)
* [日本語での説明と例](examples/swirl.html) [2020.3.31]  
英語での演習に抵抗があるかたのために、作成しました。少しずつ、英語に慣れていけるとよいですね。
* **注：** _Beginner 用の R Programming の各 Lesson の最後に、'Would you like to receive credit for completing this course on Coursera.org?' とメッセージが表示されますが、2: No を選択してください。（[`swirl` Course Repository](https://github.com/swirldev/swirl_courses#swirl-courses) 参照）_

### Various Learning Sites

> 少しずつ紹介していきます。

* Rstat by Selva Prabhakaran: http://r-statistics.co.
* Tutorials Point. 
    * Learning R Programming: https://www.tutorialspoint.com/r/index.htm
    * Big Data and Analytics Tutorials: https://www.tutorialspoint.com/big_data_tutorials.htm
    * Machine Learning: https://www.tutorialspoint.com/machine_learning_tutorials.htm
    * Mathematics for Data Science and Machine Learning Using R: (some previews) https://www.tutorialspoint.com/mathematics_for_data_science_and_machine_learning_using_r/index.asp
* R Tutorial: http://www.r-tutor.com/r-introduction
* Quick R: https://www.statmethods.net/r-tutorial/index.html
* Guru99: https://www.guru99.com/r-tutorial.html
* Cyclismo: https://www.cyclismo.org/tutorial/R/
* Edureka https://www.edureka.co/blog/r-tutorial/:
* Monash Data Fluency: https://monashdatafluency.github.io/r-intro-2/index.html
* Data carpentry https://datacarpentry.org/R-ecology-lesson/index.html. 
    * Ggplot2 https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html:
* R Tutorials: https://data-flair.training/blogs/r-tutorials-home/
* Intro R datacamp: https://learn.datacamp.com/courses/free-introduction-to-r%20. 
    * https://learn.datacamp.com/courses/data-visualization-with-ggplot2-1
* Data Quest: https://app.dataquest.io/dashboard - interactive
* W3square spaces: https://www.w3resource.com/r-programming-exercises/basic/
* Vertabelo https://academy.vertabelo.com/course/introduction-to-r 28 exercises [good]
* edX Microsoft: Introduction to R for Data Science: Data Camp. 
    * https://www.edx.org/course/introduction-to-r-for-data-science-2
* Coursera https://www.coursera.org/learn/r-programming:  
    * https://www.youtube.com/playlist?list=PLVext98k2evi8mDNRo4MwIgVgSmwM3cS8
* Harvard University Data Science Services: https://dss.iq.harvard.edu. 
    * Materials: https://dss.iq.harvard.edu/workshop-materials
* University of Michigan: https://www.socr.umich.edu/people/dinov/courses/DSPA_Topics.html. 
* UCLA: 
    * Data Science and Predictive Analytics:  Biomedical and Health Applications using R  with supporting materials (including R code)
* Data Novia Courses: https://www.datanovia.com/en/dtcourses/
* Code Academy: Learn R: https://www.codecademy.com/learn. 
    * readr, dplyr

## Data Visualization

### Graphics

* [Examples of Graphs](examples/examples_of_graphs.html): グラフの基本的な例

## Miscellaneous
